name = "monorepo-gateway"
threads = 0
log_level = "INFO"

[upstreams.rust]
addrs = ["rust:8080"]

[upstreams.typescript]
addrs = ["typescript:3000"]

[locations.api]
path = "/api"
upstream = "rust"
rewrite = "^/api/(.*) /$1"
enable_reverse_proxy_headers = true

[locations.web]
path = "/"
upstream = "typescript"
enable_reverse_proxy_headers = true

[servers.http]
addr = "0.0.0.0:80"
locations = ["api", "web"]
