name = "app-gateway"
threads = 0
log_level = "INFO"

[upstreams.server]
addrs = ["server:8080"]
health_check = "http://server:8080/health"

[upstreams.client]
addrs = ["client:3000"]

[locations.api]
path = "/api"
upstream = "server"
rewrite = "^/api/(.*) /$1"
enable_reverse_proxy_headers = true

[locations.client]
path = "/"
upstream = "client"
enable_reverse_proxy_headers = true

[servers.http]
addr = "0.0.0.0:80"
locations = ["api", "client"]
