name = "app-gateway"
threads = 0
log_level = "INFO"

[upstreams.server]
addrs = ["server:8080"]
health_check = "http://server:8080/health"

[locations.server]
path = "/"
upstream = "server"
enable_reverse_proxy_headers = true

[servers.http]
addr = "0.0.0.0:80"
locations = ["server"]
